// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'modules/homework/models/local/homework_box.dart';
import 'modules/schedule/models/local/schedule_box.dart';
import 'modules/schedule/models/local/schedule_item_box.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 9053494043617025232),
    name: 'HomeworkBox',
    lastPropertyId: const obx_int.IdUid(6, 1007424516597279154),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 157814605924391779),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1365095936950897487),
        name: 'homeworkId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 966039025658548335),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1069872847218804476),
        name: 'subject',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4601836147206682428),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 133662776536298298),
        name: 'dueDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1007424516597279154),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6774720726009855404),
    name: 'ScheduleBox',
    lastPropertyId: const obx_int.IdUid(3, 3673243315146197248),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 842901112772044309),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5223957150987982997),
        name: 'group',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3673243315146197248),
        name: 'groupId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 6893663170567280639),
        name: 'monday',
        targetId: const obx_int.IdUid(3, 8454491335270727914),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 8449219194342601396),
        name: 'tuesday',
        targetId: const obx_int.IdUid(3, 8454491335270727914),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 5448718805994984733),
        name: 'wednesday',
        targetId: const obx_int.IdUid(3, 8454491335270727914),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(4, 6137659983517564927),
        name: 'thursday',
        targetId: const obx_int.IdUid(3, 8454491335270727914),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(5, 5579319385102700080),
        name: 'friday',
        targetId: const obx_int.IdUid(3, 8454491335270727914),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8454491335270727914),
    name: 'ScheduleItemBox',
    lastPropertyId: const obx_int.IdUid(6, 224407082411132609),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1287731885767440713),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2389190963463686103),
        name: 'time',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8924481928545512967),
        name: 'subject',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2560884080895321642),
        name: 'teacher',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7191860708625728892),
        name: 'room',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 224407082411132609),
        name: 'period',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 8454491335270727914),
    lastIndexId: const obx_int.IdUid(1, 966039025658548335),
    lastRelationId: const obx_int.IdUid(5, 5579319385102700080),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    HomeworkBox: obx_int.EntityDefinition<HomeworkBox>(
      model: _entities[0],
      toOneRelations: (HomeworkBox object) => [],
      toManyRelations: (HomeworkBox object) => {},
      getId: (HomeworkBox object) => object.id,
      setId: (HomeworkBox object, int id) {
        object.id = id;
      },
      objectToFB: (HomeworkBox object, fb.Builder fbb) {
        final homeworkIdOffset = fbb.writeString(object.homeworkId);
        final subjectOffset = fbb.writeString(object.subject);
        final descriptionOffset = fbb.writeString(object.description);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, homeworkIdOffset);
        fbb.addOffset(2, subjectOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.dueDate.millisecondsSinceEpoch);
        fbb.addOffset(5, imageUrlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final homeworkIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final subjectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final dueDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = HomeworkBox(
          homeworkId: homeworkIdParam,
          subject: subjectParam,
          description: descriptionParam,
          dueDate: dueDateParam,
          imageUrl: imageUrlParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ScheduleBox: obx_int.EntityDefinition<ScheduleBox>(
      model: _entities[1],
      toOneRelations: (ScheduleBox object) => [],
      toManyRelations: (ScheduleBox object) => {
        obx_int.RelInfo<ScheduleBox>.toMany(1, object.id): object.monday,
        obx_int.RelInfo<ScheduleBox>.toMany(2, object.id): object.tuesday,
        obx_int.RelInfo<ScheduleBox>.toMany(3, object.id): object.wednesday,
        obx_int.RelInfo<ScheduleBox>.toMany(4, object.id): object.thursday,
        obx_int.RelInfo<ScheduleBox>.toMany(5, object.id): object.friday,
      },
      getId: (ScheduleBox object) => object.id,
      setId: (ScheduleBox object, int id) {
        object.id = id;
      },
      objectToFB: (ScheduleBox object, fb.Builder fbb) {
        final groupOffset = fbb.writeString(object.group);
        final groupIdOffset = fbb.writeString(object.groupId);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, groupOffset);
        fbb.addOffset(2, groupIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final groupIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final groupParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = ScheduleBox(
          id: idParam,
          groupId: groupIdParam,
          group: groupParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<ScheduleBox>(
          object.monday,
          store,
          obx_int.RelInfo<ScheduleBox>.toMany(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<ScheduleBox>(
          object.tuesday,
          store,
          obx_int.RelInfo<ScheduleBox>.toMany(2, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<ScheduleBox>(
          object.wednesday,
          store,
          obx_int.RelInfo<ScheduleBox>.toMany(3, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<ScheduleBox>(
          object.thursday,
          store,
          obx_int.RelInfo<ScheduleBox>.toMany(4, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<ScheduleBox>(
          object.friday,
          store,
          obx_int.RelInfo<ScheduleBox>.toMany(5, object.id),
        );
        return object;
      },
    ),
    ScheduleItemBox: obx_int.EntityDefinition<ScheduleItemBox>(
      model: _entities[2],
      toOneRelations: (ScheduleItemBox object) => [],
      toManyRelations: (ScheduleItemBox object) => {},
      getId: (ScheduleItemBox object) => object.id,
      setId: (ScheduleItemBox object, int id) {
        object.id = id;
      },
      objectToFB: (ScheduleItemBox object, fb.Builder fbb) {
        final timeOffset = fbb.writeString(object.time);
        final subjectOffset = fbb.writeString(object.subject);
        final teacherOffset = object.teacher == null
            ? null
            : fbb.writeString(object.teacher!);
        final roomOffset = object.room == null
            ? null
            : fbb.writeString(object.room!);
        final periodOffset = fbb.writeString(object.period);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, timeOffset);
        fbb.addOffset(2, subjectOffset);
        fbb.addOffset(3, teacherOffset);
        fbb.addOffset(4, roomOffset);
        fbb.addOffset(5, periodOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final timeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final subjectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teacherParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final roomParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final periodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = ScheduleItemBox(
          id: idParam,
          time: timeParam,
          subject: subjectParam,
          teacher: teacherParam,
          room: roomParam,
          period: periodParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [HomeworkBox] entity fields to define ObjectBox queries.
class HomeworkBox_ {
  /// See [HomeworkBox.id].
  static final id = obx.QueryIntegerProperty<HomeworkBox>(
    _entities[0].properties[0],
  );

  /// See [HomeworkBox.homeworkId].
  static final homeworkId = obx.QueryStringProperty<HomeworkBox>(
    _entities[0].properties[1],
  );

  /// See [HomeworkBox.subject].
  static final subject = obx.QueryStringProperty<HomeworkBox>(
    _entities[0].properties[2],
  );

  /// See [HomeworkBox.description].
  static final description = obx.QueryStringProperty<HomeworkBox>(
    _entities[0].properties[3],
  );

  /// See [HomeworkBox.dueDate].
  static final dueDate = obx.QueryDateProperty<HomeworkBox>(
    _entities[0].properties[4],
  );

  /// See [HomeworkBox.imageUrl].
  static final imageUrl = obx.QueryStringProperty<HomeworkBox>(
    _entities[0].properties[5],
  );
}

/// [ScheduleBox] entity fields to define ObjectBox queries.
class ScheduleBox_ {
  /// See [ScheduleBox.id].
  static final id = obx.QueryIntegerProperty<ScheduleBox>(
    _entities[1].properties[0],
  );

  /// See [ScheduleBox.group].
  static final group = obx.QueryStringProperty<ScheduleBox>(
    _entities[1].properties[1],
  );

  /// See [ScheduleBox.groupId].
  static final groupId = obx.QueryStringProperty<ScheduleBox>(
    _entities[1].properties[2],
  );

  /// see [ScheduleBox.monday]
  static final monday = obx.QueryRelationToMany<ScheduleBox, ScheduleItemBox>(
    _entities[1].relations[0],
  );

  /// see [ScheduleBox.tuesday]
  static final tuesday = obx.QueryRelationToMany<ScheduleBox, ScheduleItemBox>(
    _entities[1].relations[1],
  );

  /// see [ScheduleBox.wednesday]
  static final wednesday =
      obx.QueryRelationToMany<ScheduleBox, ScheduleItemBox>(
        _entities[1].relations[2],
      );

  /// see [ScheduleBox.thursday]
  static final thursday = obx.QueryRelationToMany<ScheduleBox, ScheduleItemBox>(
    _entities[1].relations[3],
  );

  /// see [ScheduleBox.friday]
  static final friday = obx.QueryRelationToMany<ScheduleBox, ScheduleItemBox>(
    _entities[1].relations[4],
  );
}

/// [ScheduleItemBox] entity fields to define ObjectBox queries.
class ScheduleItemBox_ {
  /// See [ScheduleItemBox.id].
  static final id = obx.QueryIntegerProperty<ScheduleItemBox>(
    _entities[2].properties[0],
  );

  /// See [ScheduleItemBox.time].
  static final time = obx.QueryStringProperty<ScheduleItemBox>(
    _entities[2].properties[1],
  );

  /// See [ScheduleItemBox.subject].
  static final subject = obx.QueryStringProperty<ScheduleItemBox>(
    _entities[2].properties[2],
  );

  /// See [ScheduleItemBox.teacher].
  static final teacher = obx.QueryStringProperty<ScheduleItemBox>(
    _entities[2].properties[3],
  );

  /// See [ScheduleItemBox.room].
  static final room = obx.QueryStringProperty<ScheduleItemBox>(
    _entities[2].properties[4],
  );

  /// See [ScheduleItemBox.period].
  static final period = obx.QueryStringProperty<ScheduleItemBox>(
    _entities[2].properties[5],
  );
}
